### ISSUE TITLE
Time function structure in GGXF header

### ISSUE THREAD

**Issue by ccrook** [opengeospatial/CRS-Deformation-Models#38]
The currently proposed time function is documented in the [functional model strawman](https://github.com/opengeospatial/CRS-Deformation-Models/blob/master/functional-model/strawman-cc/functional-model-strawman-cc.adoc#formula-time-function is a composite function calculated by adding one or more base components, each one of:

- constant
- velocity
- step (coseismic)
- reverse step (coseismic)
- piecewise linear (approximate arbitrary time evolution of deformation)
-  exponential (postseismic)
- logarithmic (postseismic)
- acceleration (long term trend eg GIA)
- hyperbolic tangent (model SSE events)
- cyclic (at one specific frequency)

This provides can support the most likely functions that we expect to be used in deformation models, based on geophysical deformation models and GNSS reference station models.  Both of these are generally based on trajectories of individual points.  The piecewise function adds a capability to approximate model arbitrarily complex functions.

To progress GGXF in a way that supports Deformation Models we need to identify what is required in it to do that.  The deformation model GGXF headers are mostly generic - little different to (for example) a datum transformation grid.  However the time function is structurally relatively complex and so we want to offer GGXF a likely draft header. 

An (unrealistic) example model to demonstrate each type is:

``` yaml


deformationTimeFunction:
  # Velocity function (startDate, endDate, and functionMultiplier are all optional)
  - timeFunctionType: velocityTimeFunction
    functionReferenceDate: 2000-01-01T00:00:00Z
    functionMultiplier: 0.001
    startDate: 1990-01-01T00:00:00Z
    endDate: 2050-01-01T00:00:00Z
  # Step function  (functionMultiplier is optional)
  - timeFunctionType: stepTimeFunction
    stepDate: 2013-05-08T00:00:00Z
    functionMultiplier: 1.0
  # Reverse step function (functionMultiplier is optional)
  - timeFunctionType: reverseStepTimeFunction 
    stepDate: 2004-11-02T00:00:00Z
    functionMultiplier: 1.0
  # Piecewise function
  - timeFunctionType: piecewiseLinearTimeFunction
    startDate: 2013-05-08T00:00:00Z
    startScaleFactor: 0.0 
    endDate: 2014-01-01T00:00:00Z
    endScaleFactor: 0.9 
  # Exponential function (endDate and functionMultiplier are optional)
  - timeFunctionType: exponentialTimeFunction
    startDate: 2013-05-08T00:00:00Z
    functionMultiplier: 1.9
    decayRate: 0.85
    endDate: 2015-12-31T00:00:00Z
  # Logarithmic function (endDate and functionMultiplier are optional)
  - timeFunctionType: logarithmicTimeFunction
    startDate: 2013-05-08T00:00:00Z
    functionMultiplier: 1.9
    timeConstant: 3.6
    endDate: 2018-12-31T00:00:00Z
  # Acceleration function (startDate, endDate and functionMultiplier are optional)
  - timeFunctionType: accelerationTimeFunction
    functionReferenceDate: 2010-01-17T00:00:00Z
    functionMultiplier: 0.13
    startDate: 2010-01-17T00:00:00Z
  # Hyperbolic tangent function (functionMultplier is optional)
  - timeFunctionType: hyperbolicTangentTimeFunction
    startDate: 2013-05-08T00:00:00Z
    endDate: 2013-09-13T00:00:00Z
    functionMultiplier: 1.0 
    timeConstant: 0.28 
  # Cyclic function
  - timeFunctionType: cyclicTimeFunction
    functionReferenceDate: 2000-01-01T00:00:00Z
    frequencyPerYear: 1
    cosineMultiplier: 0.8
    sineMultiplier: -0.37

```

I would like to have a discussion to gain team consensus on the preferred model to finalize its description in GGXF.

**Comment by ccrook** [comment]
When I started writing this I was thinking I could remove the requirement for a composite function with a model that just used one of the following base functions:

- polynomial (maybe only up to degree 2, providing constant, velocity and acceleration functions)
- piecewise linear (including step and reverse step)
- exponential 
- logarithmic
- cyclic (comprising a reference epoch one or more components each with a frequency and sine/cosine amplitudes.

My reasoning was:

The composite function is only used when the same spatial deformation model applies to the components of a time function.  So (for example) it is very unlikely there would ever be a case for a composite function including a cyclic function and a velocity function.  The seasonal deformation in the cyclic model is driven by different forces and will have a different spatial distribution to the velocity model driven by regional tectonic movement (or GIA).


But!

I suspect a composite function could still be required to represent post-seismic deformation.  It is common in geophysics to represent the post-seismic trajectory of a single point by a model summing one or more exponential and logarithmic functions.  These would most likely be different functions at different points.  Nonetheless in a deformation model we are necessarily approximating the total postseismic deformation, and we could decide that best approximation we can practically provide does include both components.

**Comment by ccrook** [comment]
## Piecewise function versus using ramp functions

This compares two options for representing piecewise linear time functions in the deformation model function and more particularly in the GGXF group header that will implement the function with a view to choosing which best suits as an implementation approach.

Piecewise functions are desired as an option the deformation model because 1) they can approximate arbitrarily complex time functions, and 2) they are used in the LINZ deformation so required to implement that. 

However when implementing into GGXF headers it raised (for me) a question of whether a simpler structure could suffice using ramp functions ...

### Option 1:  Implementation using a single function with multiple data points.  

<img src="https://user-images.githubusercontent.com/631058/123884779-24c7ca00-d9a0-11eb-8842-7d8c925aea62.png" width="400">

In a YAML style GGXF header this would look like:

``` yaml
timeFunction:
   baseFunctions:
     - type: piecewise
       epochMultipliers:
           - epoch: 2013-05-08T00:00:00Z
             multiplier: 0.0 
           - epoch: 2013-05-08T00:00:00Z
             multiplier: 0.9 
           - epoch: 2014-02-05T00:00:00Z
             multiplier: 1.2 
           - epoch: 2015-01-01T00:00:00Z
             multiplier: 1.4 
```

Pro:

* intuitive and simple
* only one base function to evaluate

Con:
* adds a second level of nesting to yaml definition so more complex structure
* little used currently (only NZ model?) so added complexity may have little use

### Option 2: Implement a simple "ramp function" base function and create the piecewise representation by adding multiple ramp functions.

A ramp function is a simple function with four parameters, startEpoch, startMultiplier, endEpoch, endMultplier

<img src="https://user-images.githubusercontent.com/631058/123886118-dec03580-d9a2-11eb-8d1b-78603e5c1b65.png" width="400">

``` yaml
timeFunction:
   baseFunctions:
     - type: ramp                                 # red function
       startEpoch: 2013-05-08T00:00:00Z
       startMultiplier: 0.0 
       endEpoch: 2013-05-08T00:00:00Z
       endMultiplier: 0.9
    - type: ramp                                  # blue function
       startEpoch: 2013-05-08T00:00:00Z
       startMultiplier: 0.0 
       endEpoch: 2014-02-05T00:00:00Z
       endMultiplier: 0.3
    - type: ramp                                  # green function
       startEpoch: 2014-02-05T00:00:00Z
       startMultiplier: 0.0
       endEpoch: 2015-01-01T00:00:00Z
       endMultiplier: 0.2
```

Pro:

* simplifies the data structure by removing one level 

Con:
* not intuitive
* less efficient to evaluate as multiple functions need to be evaluate

### Recommendation

Although GGXF implementation should not drive functional model definition the simple ramp function is preferred (after *much* vacillation)

### Meeting 2021-07-05

There was a slight preference for the simpler base function.  However the name "ramp function" generally did not resonate (and subsequent investigation shows it is different from the conventional mathematical ramp function.  

### Conclusion

The functional model will include a function type called piecewise linear function and defined just by a start and end epoch and multiplier.  (YAML example in the header updated to reflect this).

The

**Comment by ccrook** [comment]
## Overall structure

The YAML structure must support multiple time functions components.  My original proposal was 

``` yaml

groups:
  # Start of a GGXF group corresponding to a component in the deformation model 
  - remark: Deformation from 2 Feb 2013 earthquake
    timeFunction:
       # minEpoch and maxEpoch define the temporal extent within which the 
       minEpoch: 2013-02-02T11:58:00
       # maxEpoch: 2019-12-31T00:00:00
       # The time function is defined by adding one or more base functions
       baseFunctions:
         - type: step
           referenceEpoch: 2013-02-02T11:58:00
    grids:
     - remark: horizontal coseismic displacement
       ....

```

However Roger Lott has pointed out that the minEpoch and maxEpoch items are redundant as they can be calculated from the time function.  The intention of having them for computational efficiency.  When calculating the model the group can be ignored if the time is outside this temporal extent).  If they are omitted the time function must be calculated at the calculation point and then ignored if it evaluates to 0.0.  Generally this will be at small computational cost, particularly in the common case where the deformation is evaluated many times using the same calculation epoch (eg transforming a data set from one epoch to another).

If these are omitted then baseFunctions element is not required to identify the list of base time functions in the data structure.  Instead the timeFunction element can be an array itself, so that the overall structure is somewhat simpler:

``` yaml

groups:
  # Start of a GGXF group corresponding to a component in the deformation model 
  - remark: Deformation from 2 Feb 2013 earthquake
    timeFunction:
     - type: step
       referenceEpoch: 2013-02-02T11:58:00
    grids:
     - remark: horizontal coseismic displacement
       ....
```

Do we agree with this simpler structure?

Pros: 
* easier to users to create and read

Cons: 
* slightly less efficient for computation
* doesn't allow future enhancements adding new attributes to the time function

Recommendation: 

?

**Comment by ccrook** [comment]
Copied from @desruisseaux  https://github.com/opengeospatial/CRS-Gridded-Geodetic-data-eXchange-Format/issues/10#issuecomment-874582517

About the time function, a possible approach would be to decide that the timeFunction value is always an array of functions. There would be no need for explicit "piecewise" function since the array would be the piecewise function. The array length would be 1 in the simple cases. Taking the example at the beginning of this issue it could be:

``` yaml
   deformationModel
      - component
          spatialModel:
          ...
          timeFunction:
              - functionType:   linear
                startEpoch:     2015-05-02
                endEpoch:       2016-05-02
                multiplier:     1.5
              - functionType:   exponential
                startEpoch:     2016-05-02
                endEpoch:       2017-05-02
                referenceEpoch: 2010-03-04
                decayRate:      0.8
                amplitude:      1.3
              - ...
     - component
       ...
```

The array elements would be in increasing order of startEpoch. We could possibly remove the endEpoch if we specify that the end epoch of an element is implicitly the start epoch of the next element (it would avoid to worry about possible overlaps or holes in the temporal range of elements).
